VAGRANT_COMMAND = ARGV[0]
# Set a variable for the IP address and Mongo version to install at the top of the file, so we can change it easily.
ip_address = "10.10.10.68"
hostname = "mongodb-central-prod3" 
mongodb_version = "4.0"
repl_set_name = "East"
config_server = 0

Vagrant.configure("2") do |config|
  config.vm.provision "shell", path: "../common/setup.sh", args: "#{ip_address} #{hostname} #{mongodb_version} #{repl_set_name} #{config_server}"
  config.vm.synced_folder "../common/", "/common"

  # If ssh passed in, then change user to mongod
  if VAGRANT_COMMAND == "ssh"
    config.ssh.username = 'mongod'
  end
  config.vm.box = "centos/7"
 
  config.vm.network "private_network", ip: "#{ip_address}"
  config.vm.hostname = "#{hostname}" 
 
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "256"
  end
end
